/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_3 (
    input [7:0] inputA,
    input [7:0] inputB,
    input [3:0] alufn,
    output reg [7:0] out
  );
  
  
  
  always @* begin
    
    case (alufn)
      4'h1: begin
        out = ~(inputA | inputB);
      end
      4'h6: begin
        out = inputA ^ inputB;
      end
      4'h7: begin
        out = ~(inputA & inputB);
      end
      4'h8: begin
        out = inputA & inputB;
      end
      4'h9: begin
        out = ~(inputA ^ inputB);
      end
      4'ha: begin
        out = inputA;
      end
      4'hc: begin
        out = inputB;
      end
      4'he: begin
        out = inputA | inputB;
      end
      default: begin
        out = 8'h00;
      end
    endcase
  end
endmodule
